language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "iojs-v2.5.0"
  - "4.1"
before_install: "sudo apt-get update && sudo apt-get install -y pngcrush && npm install -g npm && npm cache clean"
script: "npm run-script travis"
